### PR TITLE
Remove default naming for deployer vnet

### PR DESCRIPTION
**Pull request by KimForss**
## Problem
Deployer VNet had default naming

## Solution
Removing the default naming for deployer VNet

## Tests
<Please provide steps to test the PR>

## Notes
Closes https://github.com/Azure/sap-hana/issues/750

### CODE REVIEW

**Review by YunziZhangAzure — APPROVED** [review]

**Review by rukawata — APPROVED** [review]
lgtm!

**Review by rukawata — CHANGES_REQUESTED** [review]
Please take a look at [pipeline](https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=9844&view=logs&j=3e7c2453-b9e0-5f22-4314-eb3ec9329da1&t=e6a0a175-e92e-585d-f1b1-708558137faa), it fails with error:
```
 on ../../../../s/deploy/terraform/terraform-units/modules/sap_deployer/variables_local.tf line 59, in locals:
  59:   vnet_mgmt_tempname = local.vnet_mgmt.name
    |----------------
    | local.vnet_mgmt is object with 1 attribute "subnet_mgmt"

```

**Comment by KimForss** [comment]
The pipeline error is correct behaviour - if the name is not specified the deployment should fail. 

image

**Comment by rukawata** [comment]
> The pipeline error is correct behaviour - if the name is not specified the deployment should fail.
> 
> image

I understand. Then the change of [pipeline](https://github.com/Azure/sap-hana/blob/feature/remote-tfstate/.pipeline/templates/deployer/create-deployer-steps.yml) to add vnet should be part of the PR. Please check file and make the change

**Comment by KimForss** [comment]
pipeline change made

**Comment by rukawata** [comment]
> pipeline change made

Add some additional changes in pipeline, now it runs fine :)

**Review by rukawata — APPROVED** [review]

**Pull request merged**
