### PR TITLE
correct variable type when using conditional expression 

### PR DESCRIPTION
**Pull request by YunziZhangAzure**
## Problem
<Please describe what problem this PR is trying to resolve>
See https://github.com/Azure/sap-hana/pull/832
Merge this hotfix commit to feature/keyvault as well.

## Solution
<Please elaborate the solution for the problem>

## Tests
<Please provide steps to test the PR>

## Notes
<Additional comments for the PR>

### CODE REVIEW

**Review by rukawata — COMMENTED** [review]
Sorry I did not catch this earlier in PR #832.
By not using the object, the container creation lost the dependency to the SA creation.
Therefore we see error in test [here](https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=12071&view=results). 
Same problem with feature/remote-tfstate branch, see test result [here](https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=12082&view=logs&j=d764d31b-fb26-5fc3-93b2-7fc094a2e94a&t=8b66a7ac-67d7-5b53-2853-18ed51fe316e).

I feel to force the dependency using depends_on is probably not a good idea - if possible TF should handle the dependency.
There are some creative ideas in the thread [here](https://github.com/hashicorp/terraform/issues/22405), maybe take a look. Or another option is to do the logic in the resource block instead of having a variable.

Another thing I don't have an answer yet is, when we do not reuse existing storage account, this should be the same condition mismatch between the two object, why it was not a problem?

**Comment by YunziZhangAzure** [comment]
> Sorry I did not catch this earlier in PR #832.
> By not using the object, the container creation lost the dependency to the SA creation.
> Therefore we see error in test [here](https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=12071&view=results).
> Same problem with feature/remote-tfstate branch, see test result [here](https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=12082&view=logs&j=d764d31b-fb26-5fc3-93b2-7fc094a2e94a&t=8b66a7ac-67d7-5b53-2853-18ed51fe316e).
> 
> I feel to force the dependency using depends_on is probably not a good idea - if possible TF should handle the dependency.
> There are some creative ideas in the thread [here](https://github.com/hashicorp/terraform/issues/22405), maybe take a look. Or another option is to do the logic in the resource block instead of having a variable.
> 
> Another thing I don't have an answer yet is, when we do not reuse existing storage account, this should be the same condition mismatch between the two object, why it was not a problem?

Thanks for catching this issue! I have checked the post, but it seems the scenario of them (map, list, variable) is a little different from us. One option may be applicable is to transfer the object jsoncode, which may make our codes more complex. 
so I'm including the logic in the resource block to introduce an implicit dependency between storage account and container.
Here's the test after a new commit. 
https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=12193&view=results

**Review by rukawata — APPROVED** [review]
lgtm! Thanks for fixing this!

**Comment by rukawata** [comment]
> lgtm! Thanks for fixing this!

Ah, please also fix the same in feature/remote-tfstate :)

**Pull request merged**
