### PR TITLE
Basic Implementation of mounting disks using Ansible

### PR DESCRIPTION
**Pull request by pabowers**
This implementation replaces the bash scripts that were previously used to mount the disks, set up file systems, etc.  For now, as was the case with the bash script, the configuration is limited to what is in the Ansible playbook.  The user may alter the disk configuration in Ansible if a different layout is desired.

### CODE REVIEW

**Comment by pabowers** [comment]
Sorry for the confusion all, I'm getting used to using Forking and didn't realize I was deleting my branch from my Fork.

**Comment by pabowers** [comment]
Hmm, did you pull after setting my branch as origin and go to my ansible branch?  It appears that the command run from terraform that called ansible was "'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u tniek --private-key '~/.ssh/id_tftest' -i 'tniek-tf.westus2.cloudapp.azure.com,' ansible/playbook.yml'" which isn't what should be executed.  The correct line of code that should be run is "ANSIBLE_HOST_KEY_CHECKING=\"False\" ansible-playbook -u ${var.vm_user} --private-key '${var.sshkey_path_private}' --extra-vars='{\"url_sapcar\": \"${var.url_sap_sapcar}\", \"url_hdbserver\": \"${var.url_sap_hdbserver}\", \"sap_sid\": \"${var.sap_sid}\", \"sap_instance_num\": \"${var.sap_instancenum}\", \"sap_hostname\": \"${local.vm_name}\", \"pwd_os_sapadm\": \"${var.pw_os_sapadm}\", \"pwd_os_sidadm\": \"${var.pw_os_sidadm}\", \"pwd_db_system\": \"${var.pw_db_system}\" }' -i '${local.vm_fqdn},' ansible/playbook.yml".

Without that line being executed, ansible tries to find the variables from the previously existing defaults/main.yml.

Can you tell me what 'git log' gives you?

Thanks,
Page
________________________________

**Comment by tniek** [comment]
Here’s the order of commands I used:

git remote add pabowers git@github.com:pabowers/sap-hana.git<mailto:git@github.com:pabowers/sap-hana.git>
git checkout pabowers/ansible-provision_hardware
git pull
terraform apply

‘git log’ returns the following – I don’t see your commit 64da46b…

commit cee45b77ee4a43eee99399b86e13f35c2a4e1f37 (HEAD -> pabowers/ansible-provision_hardware, origin/pabowers/ansible-provision_hardware)
Author: Page Bowers <pabowers@microsoft.com>
Date:   Wed Aug 1 18:20:07 2018 +0000

    Basic Implementation of mounting disks using Ansible

commit c8915283ceab4ea7837c7e22babd101dcf1882ea
Author: Page Bowers <40775967+pabowers@users.noreply.github.com>
Date:   Fri Aug 3 11:20:02 2018 -0700

    Add Travis CI to build (#14)

commit f8dcbf314e85443712d38905f67a1107bc9d6d04
Author: Page Bowers <40775967+pabowers@users.noreply.github.com>
Date:   Thu Aug 2 17:41:34 2018 -0700

    Fixing master's build by fixing formatting and removing dependencies on files that no longer exist (#15)

commit 453b27e2a25b586214cb9f11f99ac484015a2b97
Author: Page Bowers <pabowers@microsoft.com>
Date:   Tue Jul 31 23:25:10 2018 +0000

    Separate disk creation and attachment from VM creation

commit b4148159c60a0106c98e92ee535c51d4dc28ac45
Author: Tobias Niekamp <tniek@microsoft.com>
Date:   Tue Jul 31 14:52:00 2018 -0700

    HDB installation: Replacing bash script (called from TF) with Ansible role (#12)

    * Remove HDB install via terraform to prepare for Ansible

    * Replace bash scripts with simple Ansible playbook:
    - download required bits (SAPCAR, HDB server)
    - extract HDB server bits into /hana/shared/install

    * Prototype for Ansible role 'saphana-install'
    - integration with TF template
    - download, extract, install HDB server on VM
    - config via roles/saphana-install/defaults/main.yml

**Comment by pabowers** [comment]
I see your problem @tniek the branch you checked out doesn't exist.  It did exist on the main repo at one point, but isn't even a remote branch at this point
Try 
~~~~ 
git checkout ansible-provision_hardware
git pull
terraform apply 
~~~~

Because the branch is in my own fork, I didn't start it off with "pabowers/"

**Comment by tniek** [comment]
Worked - thanks

**Pull request merged**
