### PR TITLE
consolidate url_sap_sapcar and url_sapcar_linux

### PR DESCRIPTION
**Pull request by persiaAziz**

### CODE REVIEW

**Comment by persiaAziz** [comment]
In that case, for the sake of consistency, do we want to change url_sapcar_windows to url_sap_sapcar_windows?

**Comment by tniek** [comment]
For consistency, probably better to name it "url_sap_sapcar_linux"

**Comment by persiaAziz** [comment]
Done @tniek

**Comment by tniek** [comment]
Looks good, thanks

**Pull request merged**
